#' Generate the DE panel of the shiny app
#' @description These are the UI and server components of the DE panel of the 
#' shiny app. It is generated by including 'DE' in the panels.default argument
#' of \code{\link{generateShinyApp}}.
#' @param id the input slot that will be used to access the value
#' @param anno annotation data frame containing a match between the row names
#' of the expression.matrix (usually ENSEMBL IDs) and the gene names that
#' should be rendered within the app and in output files; this object is
#' created by \code{\link{generateShinyApp}} using the org.db specified
#' @inheritParams generateShinyApp
#' @name DEpanel
NULL

#' @rdname DEpanel
#' @export
DEpanelUI <- function(id, metadata){
  ns <- NS(id)
  
  tabPanel(
    'Differential expression',
    sidebarLayout(
      
      # Sidebar panel for inputs ----
      sidebarPanel(
        
        selectInput(ns('condition'), 'Metadata column to use:', colnames(metadata)[-1], 
                    selected = colnames(metadata)[ncol(metadata)]),
        
        # Input: Selector variables to compare
        selectInput(ns('variable1'), 'Condition 1:', unique(metadata[[ncol(metadata)]])),
        selectInput(ns('variable2'), 'Condition 2:', unique(metadata[[ncol(metadata)]]),
                    selected = unique(metadata[[ncol(metadata)]])[2]),
        
        selectInput(ns('pipeline'), 'DE pipeline:', c("edgeR", "DESeq2")),
        
        #DE thresholds
        sliderInput(ns('lfcThreshold'), label = 'logFC threshold',
                    min = 0, value = 1, max = 5, step = 0.5),
        
        sliderInput(ns('pvalThreshold'), label = 'Adjusted p-value threshold',
                    min = 0, value = 0.05, max = 0.2, step = 0.005),
        
        #Only start DE when button is pressed
        actionButton(ns('goDE'), label = 'Start DE'),
        
        #download file name and button
        textInput(ns('fileName'),'File name for download', value ='DEset.csv', placeholder = 'DEset.csv'),
        downloadButton(ns('download'), 'Download Table'),
      ),
      
      #Main panel for displaying table of DE genes
      mainPanel(
        dataTableOutput(ns('data'))
      )
    )
  )
}

#' @rdname DEpanel
#' @export
DEpanelServer <- function(id, expression.matrix, metadata, anno){
  # check whether inputs (other than id) are reactive or not
  stopifnot({
    is.reactive(expression.matrix)
    is.reactive(metadata)
    !is.reactive(anno)
  })
  
  moduleServer(id, function(input, output, session){
    
    observe({
      updateSelectInput(session, 'variable1', choices = unique(metadata()[[input[["condition"]]]]))
      updateSelectInput(session, 'variable2', choices = unique(metadata()[[input[["condition"]]]]),
                        selected = unique(metadata()[[input[["condition"]]]])[2])
    })
    
    observe({
      condition.indices <- metadata()[[input[["condition"]]]] %in% c(input[['variable1']], input[['variable2']])
      if(any(summary(as.factor(metadata()[[input[["condition"]]]][condition.indices])) < 2)){
        choices <- "edgeR"
      }else{
        choices <- c("edgeR", "DESeq2")
      }
      updateSelectInput(session, 'pipeline', choices = choices)
    })
    
    DEresults <- eventReactive(input[["goDE"]], {
      condition.indices <- metadata()[[input[["condition"]]]] %in% c(input[['variable1']], input[['variable2']])
      DEtable <- DEanalysis_edger(
        expression.matrix = expression.matrix()[, condition.indices],
        condition = metadata()[[input[["condition"]]]][condition.indices],
        var1 = input[['variable1']],
        var2 = input[['variable2']],
        anno = anno
      )
      
      DEtableSubset <- DEtable %>%
        dplyr::filter(abs(log2FC) > input[["lfcThreshold"]] & pvalAdj < input[["pvalThreshold"]])
      
      #the thresholds are returned here so that MA/volcano and table display 
      #don't use new thresholds without the button being used
      return(list('DEtable' = DEtable,
                  "DEtableSubset" = DEtableSubset,
                  'lfcThreshold' = input[["lfcThreshold"]], 
                  'pvalThreshold' = input[["pvalThreshold"]]))
    })
    
    #Define output table (only DE genes)
    output[['data']] <- renderDataTable(DEresults()$DEtableSubset)
    
    #DE data download
    output[['download']] <- downloadHandler(
      filename = function() {
        paste(input[['fileName']])
      },
      content = function(file) {
        utils::write.csv(x = DEresults()$DEtableSubset, file = file, row.names = FALSE)
      }
    )
    
    DEresults
    
  })
}

DEpanelApp <- function(){
  shinyApp(
    ui = fluidPage(DEpanelUI('RNA')),
    server = function(input, output, session){
      DEpanelServer('RNA')
    }
  )
}
