#' Generate the GRN custom integration panel of the shiny app
#' @description These are the UI and server components of the GRN custom integration 
#' panel of the shiny app. It is generated by including at least 1 row in the 
#' custom.integration parameter of \code{\link{generateShinyApp}}.
#' @inheritParams GRNpanel
#' @param comparison.table Table linking rows of expression.matrix to custom information, 
#' for example miRNAs or transcription factors.
#' @param reference.table.name Name for reference expression matrix and coordinate table
#' @param comparison.table.name Name for comparison coordinate table
#' @param seed Random seed to create reproducible GRNs
#' @return The UI and Server components of the shiny module, that can be used
#' within the UI and Server definitions of a shiny app.
#' @name GRNCustomPanel
NULL
#' @rdname GRNCustomPanel
#' @export
GRNCustomPanelUI <- function(id, reference.table.name, comparison.table.name){
  ns <- NS(id)
  
  tabPanel(
    paste0('GRN with custom integration - ',reference.table.name,' vs ',comparison.table.name),
    sidebarLayout(
      
      sidebarPanel(
        selectInput(ns("targetGenes"), "Target genes:", multiple = TRUE, choices = character(0)),
        actionButton(ns('goGRN'), label = 'Start GRN inference'),
        
        numericInput(ns("plotConnections"), "Connections to plot:", 5, 0, 100),
        textInput(ns('plotFileName'), 'File name for plot download', value ='GRNplot.html'),
        downloadButton(ns('download'), 'Download Plot'),
      ),
      
      mainPanel(
        visNetwork::visNetworkOutput(ns('plot')),
      )
    )
  )
}

#' @rdname GRNCustomPanel
#' @export
GRNCustomPanelServer <- function(id, expression.matrix, anno, comparison.table, seed = 13){
  
  stopifnot({
    !is.reactive(expression.matrix)
    !is.reactive(anno)
    !is.reactive(comparison.table)
  })
  
  moduleServer(id, function(input, output, session){

    updateSelectizeInput(session, "targetGenes", choices = anno$NAME, server = TRUE)
    
    GRNresults <- reactive({
      target.genes <- anno$ENSEMBL[match(input[["targetGenes"]], anno$NAME)]
      set.seed(seed)
      GENIE3::GENIE3(expression.matrix, targets = target.genes)
    }) %>%
      bindEvent(input[["goGRN"]])
    
    GRNplot <- reactive({
      weightMat <- GRNresults()
      
      color_regulator_reference <- '#D2E5FF'
      color_target_reference <- '#E0E0E0'
      color_regulator_nonreference <- '#ACE9B4'
      
      edges <- GENIE3::getLinkList(weightMat, input[["plotConnections"]]) %>%
        dplyr::rename(from = .data$regulatoryGene, to = .data$targetGene, value = .data$weight) %>%
        dplyr::mutate(from = as.character(.data$from), to = as.character(.data$to))
      nodes <- tibble::tibble(
        id = c(colnames(weightMat), edges$from),
        label = anno$NAME[match(id, anno$ENSEMBL)],
        group = c(rep("target", ncol(weightMat)), rep("regulator", nrow(edges))),
        color = c(rep(color_target_reference, ncol(weightMat)), rep(color_regulator_reference, nrow(edges)))
      ) %>%
        dplyr::distinct(id, .keep_all = TRUE)
      
      comparison.table.subset = comparison.table[comparison.table$Reference_ID %in% nodes$id,]
      if (nrow(comparison.table.subset)!=0){
        
        edges.comparison <- data.frame('from'=comparison.table$Reference_ID,'to'=comparison.table$Comparison_ID,'value'=(1/nrow(comparison.table))*sum(edges$value))
        nodes.comparison <- dplyr::as_tibble(data.frame('id'=comparison.table.subset$Comparison_ID,label=comparison.table.subset$Comparison_Name,'group'='table2',color = color_regulator_nonreference))
        nodes.comparison <- unique(nodes.comparison)
        nodes = rbind(nodes,nodes.comparison)
        edges = rbind(edges,edges.comparison)
      }
      
      visNetwork::visNetwork(nodes, edges)
    })
    
    output[['plot']] <- visNetwork::renderVisNetwork(GRNplot())
    
    output[['download']] <- downloadHandler(
      filename = function() {input[['plotFileName']]},
      content = function(file) {
        GRNplot() %>% visNetwork::visSave(file)
      }
    )
    
  })
}