#' Generate the GRN panel of the shiny app
#' @description These are the UI and server components of the GRN panel of the 
#' shiny app. It is generated by including 'GRN' in the panels.default argument
#' of \code{\link{generateShinyApp}}.
#' @inheritParams DEpanel
#' @return The UI and Server components of the shiny module, that can be used
#' within the UI and Server definitions of a shiny app.
#' @name GRNpanel
NULL

#' @rdname GRNpanel
#' @export
GRNpanelUI <- function(id, metadata){
  ns <- NS(id)
  
  tabPanel(
    'GRN inference',
    sidebarLayout(
      
      sidebarPanel(
        selectInput(ns('n_networks'), 'Number of networks:', 1:4),
        
        selectInput(ns('condition'), 'Metadata column to use:', colnames(metadata)[-1], 
                    selected = colnames(metadata)[ncol(metadata)]),
        selectInput(ns('samples1'), 'Samples for GRN #1:', unique(metadata[[ncol(metadata)]]),
                    selected = unique(metadata[[ncol(metadata)]]), multiple = TRUE),
        selectInput(ns('method1'), 'Inference method for GRN #1', c("GENIE3", "GNET2")),
        conditionalPanel(
          id = ns('samples2'),
          ns=ns,
          condition = "input.n_networks >= 2",
          selectInput(ns('samples2'), 'Samples for GRN #2:', unique(metadata[[ncol(metadata)]]),
                      selected = unique(metadata[[ncol(metadata)]]), multiple = TRUE),
          selectInput(ns('method2'), 'Inference method for GRN #2', c("GENIE3", "GNET2"))
        ),
        conditionalPanel(
          id = ns('samples3'),
          ns=ns,
          condition = "input.n_networks >= 3",
          selectInput(ns('samples3'), 'Samples for GRN #3:', unique(metadata[[ncol(metadata)]]),
                      selected = unique(metadata[[ncol(metadata)]]), multiple = TRUE),
          selectInput(ns('method3'), 'Inference method for GRN #3', c("GENIE3", "GNET2"))
        ),
        conditionalPanel(
          id = ns('samples4'),
          ns=ns,
          condition = "input.n_networks >= 4",
          selectInput(ns('samples4'), 'Samples for GRN #4:', unique(metadata[[ncol(metadata)]]),
                      selected = unique(metadata[[ncol(metadata)]]), multiple = TRUE),
          selectInput(ns('method4'), 'Inference method for GRN #4', c("GENIE3", "GNET2"))
        ),
        
        selectInput(ns("regulators"), "Target genes:", multiple = TRUE, choices = character(0)),
        actionButton(ns('goGRN'), label = 'Start GRN inference'),
        
        numericInput(ns("plotConnections"), "Connections to plot:", 5, 0, 100),
        textInput(ns('plotFileName'), 'File name for plot download', value ='GRNplot.html'),
        selectInput(ns('plotId'), 'Select plot to download:', 1:4),
        downloadButton(ns('download'), 'Download Plot'),
      ),
      
      mainPanel(
        fluidRow(
          column(6, visNetwork::visNetworkOutput(ns('plot1'))),
          column(6, visNetwork::visNetworkOutput(ns('plot2')))
        ),
        conditionalPanel(
          id = ns('plotrow'),
          ns = ns,
          condition = "input.n_networks >= 3",
          fluidRow(
            column(6, visNetwork::visNetworkOutput(ns('plot3'))),
            column(6, visNetwork::visNetworkOutput(ns('plot4')))
          )
        ),
        conditionalPanel(
          id = ns('includeUpset'),
          ns = ns,
          condition = "input.n_networks > 1",
          plotOutput(ns('plotUpset'))
        )
      )
    )
  )
}

#' @rdname GRNpanel
#' @export
GRNpanelServer <- function(id, expression.matrix, metadata, anno){
  
  stopifnot({
    is.reactive(expression.matrix)
    is.reactive(metadata)
    !is.reactive(anno)
  })
  
  moduleServer(id, function(input, output, session){
    
    updateSelectizeInput(session, "regulators", choices = anno$NAME, server = TRUE)
    observe(updateSelectInput(session, "plotId", choices = seq_len(input[["n_networks"]])))
    # fix crash when no samples are selected
    GRNresults1 <- reactive({
      shinyjs::disable("goGRN")
      infer_GRN(
        expression.matrix = expression.matrix(), 
        metadata = metadata(), 
        anno = anno, 
        regulators = input[["regulators"]], 
        condition = input[["condition"]], 
        samples = input[["samples1"]], 
        inference_method = input[["method1"]]
      )
    }) %>%
      bindCache(metadata(), input[["regulators"]], input[["condition"]], 
                input[["samples1"]], input[["method1"]]) %>%
      bindEvent(input[["goGRN"]])
    GRNresults2 <- reactive({
      shinyjs::disable("goGRN")
      infer_GRN(
        expression.matrix = expression.matrix(), 
        metadata = metadata(), 
        anno = anno, 
        regulators = input[["regulators"]], 
        condition = input[["condition"]], 
        samples = input[["samples2"]], 
        inference_method = input[["method2"]]
      )
    }) %>%
      bindCache(metadata(), input[["regulators"]], input[["condition"]], 
                input[["samples2"]], input[["method2"]]) %>%
      bindEvent(input[["goGRN"]])
    GRNresults3 <- reactive({
      shinyjs::disable("goGRN")
      infer_GRN(
        expression.matrix = expression.matrix(), 
        metadata = metadata(), 
        anno = anno, 
        regulators = input[["regulators"]], 
        condition = input[["condition"]], 
        samples = input[["samples3"]], 
        inference_method = input[["method3"]]
      )
    }) %>%
      bindCache(metadata(), input[["regulators"]], input[["condition"]], 
                input[["samples3"]], input[["method3"]]) %>%
      bindEvent(input[["goGRN"]])
    GRNresults4 <- reactive({
      shinyjs::disable("goGRN")
      infer_GRN(
        expression.matrix = expression.matrix(), 
        metadata = metadata(), 
        anno = anno, 
        regulators = input[["regulators"]], 
        condition = input[["condition"]], 
        samples = input[["samples4"]], 
        inference_method = input[["method4"]]
      )
    }) %>%
      bindCache(metadata(), input[["regulators"]], input[["condition"]], 
                input[["samples4"]], input[["method4"]]) %>%
      bindEvent(input[["goGRN"]])
    
    weightMatList <- reactive({
      n_networks <- input[["n_networks"]]
      weightMatList <- list(GRNresults1())
      if(n_networks >= 2) {
        weightMatList[[2]] <- GRNresults2()
        if(n_networks >= 3) {
          weightMatList[[3]] <- GRNresults3()
        }
        if(n_networks >= 4) {
          weightMatList[[4]] <- GRNresults4()
        }
      }
      weightMatList
    })
    
    recurring_targets <- reactive({
      shinyjs::enable("goGRN")
      find_targets_with_recurring_edges(weightMatList(), input[["plotConnections"]])
    })
    
    GRNplot1 <- reactive(plot_GRN(
      weightMat = GRNresults1(), 
      anno = anno, 
      plotConnections = input[["plotConnections"]], 
      plot_position_grid = 1, 
      n_networks = input[["n_networks"]],
      recurring_targets = recurring_targets()
    )) %>%
      bindEvent(input[["goGRN"]], input[["plotConnections"]])
    GRNplot2 <- reactive(plot_GRN(
      weightMat = GRNresults2(), 
      anno = anno, 
      plotConnections = input[["plotConnections"]], 
      plot_position_grid = 2, 
      n_networks = input[["n_networks"]],
      recurring_targets = recurring_targets()
    )) %>%
      bindEvent(input[["goGRN"]], input[["plotConnections"]])
    GRNplot3 <- reactive(plot_GRN(
      weightMat = GRNresults3(), 
      anno = anno, 
      plotConnections = input[["plotConnections"]], 
      plot_position_grid = 3, 
      n_networks = input[["n_networks"]],
      recurring_targets = recurring_targets()
    )) %>%
      bindEvent(input[["goGRN"]], input[["plotConnections"]])
    GRNplot4 <- reactive(plot_GRN(
      weightMat = GRNresults4(), 
      anno = anno, 
      plotConnections = input[["plotConnections"]], 
      plot_position_grid = 4, 
      n_networks = input[["n_networks"]],
      recurring_targets = recurring_targets()
    )) %>%
      bindEvent(input[["goGRN"]], input[["plotConnections"]])
    
    upsetPlot <- reactive(plot_upset(weightMatList(), input[["plotConnections"]]))
    
    output[['plot1']] <- visNetwork::renderVisNetwork(GRNplot1())
    output[['plot2']] <- visNetwork::renderVisNetwork(GRNplot2())
    output[['plot3']] <- visNetwork::renderVisNetwork(GRNplot3())
    output[['plot4']] <- visNetwork::renderVisNetwork(GRNplot4())
    output[['plotUpset']] <- renderPlot(upsetPlot())
    
    output[['download']] <- downloadHandler(
      filename = function() {input[['plotFileName']]},
      content = function(file) {
        GRNplot <- get(paste0("GRNplot", input[["plotId"]]))()
        GRNplot %>% visNetwork::visSave(file)
      }
    )
    
  })
}