#' Generate the sample select panel of the shiny app
#' @description These are the UI and server components of the sample selection
#' panel of the shiny app. It is generated by including 'SampleSelect' in the 
#' panels.default argument of \code{\link{generateShinyApp}}.
#' @inheritParams DEpanel
#' @name sampleSelectPanel
NULL

#' @rdname sampleSelectPanel
#' @export
sampleSelectPanelUI <- function(id){
  ns <- NS(id)
  
  tabPanel(
    'Sample select',
    DT::dataTableOutput(ns('tbl'))
  )
}

#' @rdname sampleSelectPanel
#' @export
sampleSelectPanelServer <- function(id, expression.matrix, metadata){
  # check whether inputs (other than id) are reactive or not
  stopifnot({
    !is.reactive(expression.matrix)
    !is.reactive(metadata)
  })
  
  moduleServer(id, function(input, output, session){
    # output[["tbl"]] <- DT::renderDataTable({
    #   addCheckboxButtons <- paste0(
    #     '<input type="checkbox" name="row', 
    #     seq_len(nrow(metadata)), 
    #     '" value="', 
    #     seq_len(nrow(metadata)), 
    #     '">', 
    #     ""
    #   )
    #   cbind(Selected = addCheckboxButtons, metadata)
    # }, callback = htmlwidgets::JS(
    #   "function(table) {
    #     table.on('change.dt', 'tr td input:checkbox', function() {
    #       setTimeout(function () {
    #         Shiny.onInputChange('rows', $(this).add('tr td input:checkbox:checked').parent().siblings(':last-child').map(function() {
    #           return $(this).text();
    #         }).get())
    #       }, 10); 
    #     });
    #   }"
    # ),
    # escape = FALSE
    # )
  })
}

QCpanelApp <- function(){
  shinyApp(
    ui = fluidPage(QCpanelUI('qc', metadata)),
    server = function(input, output, session){
      QCpanelServer('qc', expression.matrix, metadata)
    }
  )
}